py_binary(
    name = "py1",
    srcs = ["py1.py"],
)

py_test(
   name = "test_eq",
   srcs = ["test/test_eq.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_add",
   srcs = ["test/test_add.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_conj",
   srcs = ["test/test_conj.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_mul",
   srcs = ["test/test_mul.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_div",
   srcs = ["test/test_div.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_polar",
   srcs = ["test/test_polar.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_pow",
   srcs = ["test/test_pow.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_root",
   srcs = ["test/test_root.py"],
   deps = [":py1"],
   imports = ["."],
)

py_test(
   name = "test_ln",
   srcs = ["test/test_ln.py"],
   deps = [":py1"],
   imports = ["."],
)
