py_binary(
    name = "ode1",
    srcs = ["ode1.py"],
    imports = ["."],
)

py_binary(
    name = "examples",
    srcs = [
        "examples.py",
        "books_ref.py"
    ],
    imports = ["."],
)
